export const events = {
    GET_DECKS: 'GET_DECKS',
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    REGISTER: 'REGISTER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    ERROR: 'ERROR',
    WARNING: 'WARNING',
};